export type CurrencyInfo = { name: string; exponent: number };

export const CURRENCIES: Record<string, CurrencyInfo> = {
  USD: { name: "US Dollar", exponent: 2 },
  EUR: { name: "Euro", exponent: 2 },
  GBP: { name: "British Pound", exponent: 2 },
  INR: { name: "Indian Rupee", exponent: 2 },
  BDT: { name: "Bangladeshi Taka", exponent: 2 },
  AED: { name: "UAE Dirham", exponent: 2 },
  SAR: { name: "Saudi Riyal", exponent: 2 },
  QAR: { name: "Qatari Riyal", exponent: 2 },
  KWD: { name: "Kuwaiti Dinar", exponent: 3 },
  OMR: { name: "Omani Rial", exponent: 3 },
  BHD: { name: "Bahraini Dinar", exponent: 3 },
  SGD: { name: "Singapore Dollar", exponent: 2 },
  MYR: { name: "Malaysian Ringgit", exponent: 2 },
  THB: { name: "Thai Baht", exponent: 2 },
  IDR: { name: "Indonesian Rupiah", exponent: 2 },
  PHP: { name: "Philippine Peso", exponent: 2 },
  VND: { name: "Vietnamese Dong", exponent: 0 },
  JPY: { name: "Japanese Yen", exponent: 0 },
  CNY: { name: "Chinese Yuan", exponent: 2 },
  HKD: { name: "Hong Kong Dollar", exponent: 2 },
  KRW: { name: "South Korean Won", exponent: 0 },
  AUD: { name: "Australian Dollar", exponent: 2 },
  NZD: { name: "New Zealand Dollar", exponent: 2 },
  CAD: { name: "Canadian Dollar", exponent: 2 },
  CHF: { name: "Swiss Franc", exponent: 2 },
  SEK: { name: "Swedish Krona", exponent: 2 },
  NOK: { name: "Norwegian Krone", exponent: 2 },
  DKK: { name: "Danish Krone", exponent: 2 },
  PLN: { name: "Polish Zloty", exponent: 2 },
  CZK: { name: "Czech Koruna", exponent: 2 },
  HUF: { name: "Hungarian Forint", exponent: 2 },
  TRY: { name: "Turkish Lira", exponent: 2 },
  ZAR: { name: "South African Rand", exponent: 2 },
  NGN: { name: "Nigerian Naira", exponent: 2 },
  KES: { name: "Kenyan Shilling", exponent: 2 },
  GHS: { name: "Ghanaian Cedi", exponent: 2 },
  EGP: { name: "Egyptian Pound", exponent: 2 },
  MAD: { name: "Moroccan Dirham", exponent: 2 },
  BRL: { name: "Brazilian Real", exponent: 2 },
  MXN: { name: "Mexican Peso", exponent: 2 },
  ARS: { name: "Argentine Peso", exponent: 2 },
  CLP: { name: "Chilean Peso", exponent: 0 },
  COP: { name: "Colombian Peso", exponent: 2 },
  PKR: { name: "Pakistani Rupee", exponent: 2 },
  NPR: { name: "Nepalese Rupee", exponent: 2 },
  LKR: { name: "Sri Lankan Rupee", exponent: 2 },
  ILS: { name: "Israeli Shekel", exponent: 2 },
  RON: { name: "Romanian Leu", exponent: 2 },
};